apiVersion: v1
kind: ConfigMap
metadata:
  name: melissa-bot-config
data:
  DEBUG: ${DEBUG}
  DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
  WIPE_COMMANDS_ON_EXIT: ${WIPE_COMMANDS_ON_EXIT}
  TZ: ${TZ}
---
apiVersion: v1
kind: Pod
metadata:
  name: melissa-bot
  labels:
    app: melissa-bot,pod

spec:
  containers:
  - name: main
    image: github.com/kaueabade/melissa-bot:latest
    envFrom:
    - configMapRef:
        name: melissa-bot-config